import React, { ReactNode } from "react";
import {StreamVideoProvider} from "@/app/providers/streamClientProvider";
import {Metadata} from "next"
export const metadata: Metadata = {
  title: "Recky Room",
  description: "Generated by create next app",
  icons:{
    icons:"/icons/logo.svg"
  }
};

export default function layout({ children }: { children: ReactNode }) {
  return(
    <main>
    <StreamVideoProvider>{children}</StreamVideoProvider>
  </main>
  )
  
}
